name: RankStealSMP
version: 1.0
main: me.ranksteal.RankStealPlugin
api-version: 1.21

commands:
  rank:
    description: Check rank
  setrank:
    description: Set rank
    permission: ranksteal.admin

permissions:
  ranksteal.admin:
    default: op